
# set var into gedit ~/.profile and save use source start changed
# export PATH=$PATH:/root/BPI-BIT-MPy/xtensa-esp32-elf/bin
# export IDF_PATH=/root/BPI-BIT-MPy/esp-idf

#ESPIDF = /root/BPI-BIT-MPy/esp-idf 
#PORT = /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
#CROSS_COMPILE = xtensa-esp32-elf-

include Makefile
