
# set var into gedit ~/.profile and save
#export PATH=$PATH:/root/esp32/xtensa-esp32-elf/bin
#export IDF_PATH=/root/esp32/esp-idf

#ESPIDF = /root/esp32/esp-idf 
#PORT = /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
#CROSS_COMPILE = xtensa-esp32-elf-

include Makefile
